### ISSUE TITLE
Cannot connect to BPL devnet

### ISSUE THREAD

**Issue by billotronic** [blockpool-io/bpl-client#1]
Trying to get this to work. I added the network hash and peers here::

https://github.com/billotronic/ark-client/commit/6dc4fa4521cc414183cdcf229d6d8193c3a2df24

and this is what I get

```
ark> connect devnet
Node: 13.115.247.36:4000, height: undefined
ark devnet> 

/usr/lib/node_modules/ark-client/index.js:108
      var respeers = JSON.parse(body).peers.map(function(peer){
                                           ^

TypeError: Cannot read property 'map' of undefined
    at Request._callback (/usr/lib/node_modules/ark-client/index.js:108:44)
    at Request.self.callback (/usr/lib/node_modules/ark-client/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/usr/lib/node_modules/ark-client/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/ark-client/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)


```
The client connects fine to the ark mainnet. Not sure where to go from here

```
r00t@spiderskullisland Downloads]$ node -v

v6.9.2

```
```
[r00t@spiderskullisland Downloads]$ uname -a

Linux spiderskullisland 4.11.8-1-MANJARO #1 SMP PREEMPT Fri Jun 30 06:55:31 UTC 2017 x86_64 GNU/Linux
```

**Comment by cyrus19901** [comment]
It is configured to connect to the testnet
