### ISSUE TITLE
Voting from bpl-client fails

### ISSUE THREAD

**Issue by Isabello** [blockpool-io/bpl-client#5]
```
bpl 127.0.0.1:4000> account vote isabella
passphrase: *****************************************************************************
readline.js:982
            throw err;
            ^

TypeError: Cannot read property 'createVote' of undefined
    at /home/lisk/bpl-client/index.js:399:42
    at nextTask (/home/lisk/bpl-client/node_modules/async/dist/async.js:5297:14)
    at next (/home/lisk/bpl-client/node_modules/async/dist/async.js:5304:9)
    at /home/lisk/bpl-client/node_modules/async/dist/async.js:906:16
    at /home/lisk/bpl-client/index.js:390:20
    at cb (/home/lisk/bpl-client/node_modules/vorpal/dist/vorpal.js:552:9)
    at /home/lisk/bpl-client/node_modules/vorpal/dist/vorpal.js:573:9
    at .completed (/home/lisk/bpl-client/node_modules/vorpal/dist/ui.js:220:13)
    at PromptUI.onCompletion (/home/lisk/bpl-client/node_modules/inquirer/lib/ui/prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/home/lisk/bpl-client/node_modules/rx-lite/rx.lite.js:1550:12)
lisk@bplnode:~/bpl-client$
```

The index.js file is pointing at `bpljs.delegate.createVote`. this is wrong, it should point at `bpljs.votes.createVote`

However, when this is updated to point to the correct library, it uncovers a new error. This error is logged upstream on bpljs as its an issue there: https://github.com/blockpool-io/BPL-js/issues/4

**Comment by cyrus19901** [comment]
This issue has been fixed.
